{
 "title": "Weather",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "location",
    "query": {
     "query": "SELECT\n  \"location\"\nFROM\n  \"weather\"\nWHERE\n  \"time\" >= $__timeFrom\n  AND \"time\" <= $__timeTo"
    }
   }
  ]
 },
 "panels": [
  { "title": "Sensors status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$location",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "repeat": "location",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  COUNT(temperature)\nFROM weather\nWHERE time >= now() - INTERVAL '5 minutes' AND location = '$location'\nGROUP BY time"
    }
   ]
  },
  { "title": "Air Quality", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Air Pollution Level",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  date_bin_gapfill(INTERVAL '1 minute', time) AS time,\n  location,\n  CASE\n    WHEN AVG(air_quality_pm2_5) BETWEEN 0 AND 12.0 THEN ROUND(((50.0 - 0.0)/(12.0 - 0.0)) * (AVG(air_quality_pm2_5) - 0.0) + 0.0)\n    WHEN AVG(air_quality_pm2_5) BETWEEN 12.1 AND 35.4 THEN ROUND(((100.0 - 51.0)/(35.4 - 12.1)) * (AVG(air_quality_pm2_5) - 12.1) + 51.0)\n    WHEN AVG(air_quality_pm2_5) BETWEEN 35.5 AND 55.4 THEN ROUND(((150.0 - 101.0)/(55.4 - 35.5)) * (AVG(air_quality_pm2_5) - 35.5) + 101.0)\n    ELSE NULL\n  END AS aqi\n\nFROM weather\nWHERE\n  air_quality_pm2_5 != 0\n  AND air_quality_pm10 != 0\n  AND (\n    '${location:csv}' = 'All' OR POSITION(location IN '${location:csv}') > 0\n  )\n  AND time >= $__timeFrom AND time <= $__timeTo\nGROUP BY date_bin_gapfill(INTERVAL '1 minute', time), location\nORDER BY time\n"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 5 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  date_bin_gapfill(INTERVAL '1 minute', time) AS time,\n  location,\n  interpolate(AVG(CASE \n    WHEN air_quality_pm10 BETWEEN 0 AND 20 THEN air_quality_pm10 \n    ELSE NULL \n  END)) AS pm10,\n  interpolate(AVG(CASE \n    WHEN air_quality_pm2_5 BETWEEN 0 AND 20 THEN air_quality_pm2_5 \n    ELSE NULL \n  END)) AS pm2_5\nFROM weather\nWHERE\n  (\n    '${location:csv}' = 'All' OR POSITION(location IN '${location:csv}') > 0\n  )\n  AND \"time\" >= $__timeFrom\n  AND \"time\" <= $__timeTo\n  AND air_quality_pm2_5 != 0\n  AND air_quality_pm10 != 0\nGROUP BY date_bin_gapfill(INTERVAL '1 minute', time), location\nORDER BY time"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  date_bin_gapfill(INTERVAL '1 minute', time) AS time,\n  location,\n  interpolate(AVG(air_quality_pm2_5)) AS pm2_5,\n  interpolate(AVG(air_quality_pm10)) AS pm10,\n  \n  CASE\n    WHEN AVG(air_quality_pm2_5) BETWEEN 0 AND 12.0 THEN ROUND(((50.0 - 0.0)/(12.0 - 0.0)) * (AVG(air_quality_pm2_5) - 0.0) + 0.0)\n    WHEN AVG(air_quality_pm2_5) BETWEEN 12.1 AND 35.4 THEN ROUND(((100.0 - 51.0)/(35.4 - 12.1)) * (AVG(air_quality_pm2_5) - 12.1) + 51.0)\n    WHEN AVG(air_quality_pm2_5) BETWEEN 35.5 AND 55.4 THEN ROUND(((150.0 - 101.0)/(55.4 - 35.5)) * (AVG(air_quality_pm2_5) - 35.5) + 101.0)\n    ELSE NULL\n  END AS aqi\n\nFROM weather\nWHERE\n  air_quality_pm2_5 != 0\n  AND air_quality_pm10 != 0\n  AND (\n    '${location:csv}' = 'All' OR POSITION(location IN '${location:csv}') > 0\n  )\n  AND time >= $__timeFrom AND time <= $__timeTo\nGROUP BY date_bin_gapfill(INTERVAL '1 minute', time), location\nORDER BY time\n"
    }
   ]
  },
  { "title": "Dew point", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "$location",
   "type": "stat",
   "description": "Indicate comfort, mold risk, or fog potential:\n\n< 0    : Very dry (cold, desert-like air)      \n0 – 10 : Dry air (comfortable in cool climates)\n10 – 16: Comfortable indoor air                \n16 – 18: A bit humid                           \n18 – 21: Sticky or humid                       \n> 21   : Very humid (tropical, uncomfortable)  \n> 24   : Oppressive (high mold risk indoors)   ",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 14 },
   "repeat": "location",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  (temperature - ((100 - humidity) / 5.0)) AS dew_point\nFROM weather\nWHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo\nORDER BY time"
    }
   ]
  },
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  date_bin_gapfill(INTERVAL '1 minute', time) AS time,\n  location,\n  interpolate(AVG(CASE \n    WHEN temperature BETWEEN -10 AND 50 THEN temperature \n    ELSE NULL \n  END)) AS temperature\nFROM weather\nWHERE\n  \n  (\n    '${location:csv}' = 'All' OR POSITION(location IN '${location:csv}') > 0\n  )\n  AND \"time\" >= $__timeFrom\n  AND \"time\" <= $__timeTo\nGROUP BY date_bin_gapfill(INTERVAL '1 minute', time), location\nORDER BY time"
    }
   ]
  },
  {
   "title": "${location}",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "repeat": "location",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"temperature\" FROM \"weather\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"location\" = '$location' ORDER BY time"
    }
   ]
  },
  {
   "title": "${location}",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "repeat": "location",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  MAX(temperature) AS max,\n  MIN(temperature) AS min,\n AVG(temperature) - ((0.55 - (0.0055 * AVG(humidity))) * (AVG(temperature) - 14.5)) AS \"feels like\"\nFROM weather\nWHERE time >= now() - INTERVAL '1 day' AND \"location\" = '$location'\n"
    }
   ]
  },
  { "title": "Humidity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  date_bin_gapfill(INTERVAL '1 minute', time) AS time,\n  location,\n  interpolate(AVG(CASE \n    WHEN humidity BETWEEN 20 AND 90 THEN humidity \n    ELSE NULL \n  END)) AS humidity\nFROM weather\nWHERE\n  \n  (\n    '${location:csv}' = 'All' OR POSITION(location IN '${location:csv}') > 0\n  )\n  AND \"time\" >= $__timeFrom\n  AND \"time\" <= $__timeTo\nGROUP BY date_bin_gapfill(INTERVAL '1 minute', time), location\nORDER BY time"
    }
   ]
  },
  {
   "title": "${location}",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "repeat": "location",
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  MAX(humidity) AS max,\n  MIN(humidity) AS min\nFROM weather\nWHERE time >= now() - INTERVAL '1 day' AND \"location\" = '$location'\n"
    }
   ]
  },
  {
   "title": "${location}",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
   "repeat": "location",
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  MAX(humidity) AS max,\n  MIN(humidity) AS min,\n  (\n    (6.112 * POWER(2.71828, (17.67 * AVG(temperature)) / (AVG(temperature) + 243.5)) * AVG(humidity) * 2.1674)\n    / (273.15 + AVG(temperature))\n  ) AS \"absolute humidity\"\nFROM weather\nWHERE time >= now() - INTERVAL '1 day' AND \"location\" = '$location'\n"
    }
   ]
  },
  { "title": "Pressure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  date_bin_gapfill(INTERVAL '1 minute', time) AS time,\n  location,\n  interpolate(AVG(CASE \n    WHEN pressure BETWEEN 100000 AND 104000 THEN pressure \n    ELSE NULL \n  END)) AS pressure\nFROM weather\nWHERE\n  \n  (\n    '${location:csv}' = 'All' OR POSITION(location IN '${location:csv}') > 0\n  )\n  AND \"time\" >= $__timeFrom\n  AND \"time\" <= $__timeTo\nGROUP BY date_bin_gapfill(INTERVAL '1 minute', time), location\nORDER BY time"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  date_bin_gapfill(INTERVAL '1 hour', time) AS time,\n  AVG(pressure) +\n    CASE\n      WHEN MAX(pressure) - MIN(pressure) > 1 THEN 1\n      WHEN MAX(pressure) - MIN(pressure) < -1 THEN -1\n      ELSE 0\n    END AS pressure_trend\nFROM weather\nWHERE\n  time >= $__timeFrom AND time <= now() + INTERVAL '1 hour'\nGROUP BY date_bin_gapfill(INTERVAL '1 hour', time)\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "Rough barometric forecast estimate",
   "type": "stat",
   "description": "Trend:\n- Rising (↑): Improving weather\n- Falling (↓): Rain or storm possible\n- Steady (→): Stable conditions",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  (SELECT pressure FROM weather WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo ORDER BY time DESC LIMIT 1) -\n  (SELECT pressure FROM weather WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo - INTERVAL '3 hours' ORDER BY time DESC LIMIT 1)\n  AS pressure_delta\nFROM \"weather\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"location\" = 'living-room' ORDER BY time"
    }
   ]
  },
  {
   "title": "${location}",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 41 },
   "repeat": "location",
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"pressure\" FROM \"weather\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"location\" = '$location' ORDER BY time"
    }
   ]
  },
  {
   "title": "${location}",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "repeat": "location",
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  MAX(pressure) AS max,\n  MIN(pressure) AS min\nFROM weather\nWHERE time >= now() - INTERVAL '1 day' AND \"location\" = '$location'\n"
    }
   ]
  }
 ]
}