apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.16.1/cert-manager.yaml
  - ./letsencrypt-staging.yaml
  - ./letsencrypt-production.yaml

secretGenerator:
  - name: cloudflare-secrets
    envs:
      - ./cloudflare-secrets.env
