apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-certificate
  namespace: cert-manager
spec:
  secretName: wildcard-certificate
  commonName: '*.homie.e10n.me'
  dnsNames:
    - '*.homie.e10n.me'
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
    group: cert-manager.io
  secretTemplate:
    annotations:
      replicator.v1.mittwald.de/replicate-to: "harbor"
