apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
spec:
  strategy:
    type: RollingUpdate
  template:
    spec:
      serviceAccountName: jellyfin
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        supplementalGroups:
          - 44 # video group
      containers:
        - name: jellyfin
          image: lscr.io/linuxserver/jellyfin:2021.12.16
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8096
              protocol: TCP
          env:
            - name: UMASK_SET
              value: "022"
            - name: DOCKER_MODS
              value: linuxserver/mods:jellyfin-opencl-intel
            - name: TZ
              value: "Europe/Amsterdam"
          resources:
            requests:
              cpu: 100m
              memory: 2Gi
            limits:
              cpu: 8000m
          securityContext:
            privileged: true
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
            - name: dri
              mountPath: /dev/dri
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: jellyfin-config
        - name: downloads
          persistentVolumeClaim:
            claimName: downloads
        - name: dri
          hostPath:
            path: /dev/dri
