apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - http-route.yaml
  - pvc.yaml
  - reference-grant.yaml
  - service.yaml
  - serviceaccount.yaml

labels:
  - includeSelectors: true
    pairs:
      app: jellyfin
