apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./flaresolverr/
  - ./jackett/
  - ./jellyfin/
  - ./qbittorrent/
  - ./radarr/
  - ./sonarr/
  - pvc.yaml
  - namespace.yaml

namespace: torrents
