apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - namespace.yaml
  - pvc.yaml
  - service.yaml
  - serviceaccount.yaml

namespace: n8n

labels:
  - includeSelectors: true
    pairs:
      app: n8n
