apiVersion: v1
kind: Secret
metadata:
  name: client-info-secret
type: Opaque
stringData:
  client-info.yml: |
    clients:
    - host: 192.168.94.245
      port: 5001
      https: true
      username: torrent
      password: PLACEHOLDER
