apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/SynologyOpenSource/synology-csi/v1.2.0/deploy/kubernetes/v1.20/node.yml
  - https://raw.githubusercontent.com/SynologyOpenSource/synology-csi/v1.2.0/deploy/kubernetes/v1.20/csi-driver.yml
  - https://raw.githubusercontent.com/SynologyOpenSource/synology-csi/v1.2.0/deploy/kubernetes/v1.20/controller.yml
  - namespace.yaml
  - storageclass.yaml
  - client-info-secret.yaml

patches:
  - path: node.patch.yaml

namespace: synology-csi

configMapGenerator:
  - name: synology-chroot-override
    files:
      - chroot.sh
    options:
      disableNameSuffixHash: true
