kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: synology-csi-node
  namespace: synology-csi
spec:
  template:
    spec:
      containers:
        - name: csi-plugin
          args:
            - --nodeid=$(KUBE_NODE_NAME)
            - --endpoint=$(CSI_ENDPOINT)
            - --client-info
            - /etc/synology/client-info.yml
            - --log-level=info
            - --chroot-dir=/host
            - --iscsiadm-path=/usr/local/sbin/iscsiadm
