apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
spec:
  strategy:
    type: RollingUpdate
  template:
    spec:
      serviceAccountName: radarr
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:5.21.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 7878
              protocol: TCP
          env:
            - name: UMASK_SET
              value: "022"
            - name: PUID
              value: "0"
            - name: PGID
              value: "0"
            - name: TZ
              value: "Europe/Amsterdam"
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads/torrents
              subPath: torrents
            - name: downloads
              mountPath: /downloads/movies
              subPath: movies
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: radarr-config
        - name: downloads
          persistentVolumeClaim:
            claimName: downloads
