apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: telegraf
spec:
  isCA: false
  commonName: telegraf
  secretName: telegraf-certs
  issuerRef:
    name: selfsigned-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - digital signature
    - key encipherment
    - client auth
