apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
spec:
  strategy:
    type: RollingUpdate
  template:
    spec:
      serviceAccountName: telegraf
      containers:
        - name: telegraf
          image: telegraf:1.35.4-alpine
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: telegraf-secrets
            - secretRef:
                name: influxdb-admin-token
          securityContext:
            runAsNonRoot: true
            runAsUser: 100
            runAsGroup: 101
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: config
              mountPath: /etc/telegraf/
      volumes:
        - name: config
          configMap:
            name: telegraf-config
