apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - certificate.yaml
  - deployment.yaml
  - serviceaccount.yaml

secretGenerator:
  - name: telegraf-secrets
    envs:
      - ./telegraf-secrets.env

configMapGenerator:
  - name: telegraf-config
    files:
      - telegraf.conf

labels:
  - includeSelectors: true
    pairs:
      app: telegraf
