apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: otaflux
spec:
  isCA: false
  commonName: otaflux.homie.e10n.me
  dnsNames:
    - otaflux.homie.e10n.me
  secretName: otaflux-certs
  issuerRef:
    name: selfsigned-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - digital signature
    - key encipherment
    - server auth
