apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: otaflux
spec:
  parentRefs:
    - name: eg
      sectionName: https
      namespace: gateway
  hostnames:
    - otaflux.homie.e10n.me
  rules:
    - backendRefs:
        - name: otaflux
          namespace: otaflux
          port: 80
      timeouts:
        # increase default 15s timeout to 10minutes to prevent the connection
        # to drop while the firmware is being streamed to the devices
        request: 600s
