apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - certificate.yaml
  - http-route.yaml
  - namespace.yaml
  - reference-grant-certs.yaml
  - reference-grant-service.yaml

namespace: otaflux

labels:
  - includeSelectors: true
    pairs:
      app: otaflux

helmCharts:
  - name: otaflux
    repo: oci://ghcr.io/etiennetremel/helm-charts
    version: v0.1.2
    releaseName: otaflux
    namespace: otaflux
    valuesFile: otaflux-values.yaml
