apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - certificate.yaml
  - deployment.yaml
  - namespace.yaml
  - service.yaml
  - serviceaccount.yaml

namespace: otaflux

labels:
  - includeSelectors: true
    pairs:
      app: otaflux

secretGenerator:
  - name: otaflux-secrets
    envs:
      - ./otaflux-secrets.env
