otaflux:
  registryUrl: harbor.example.com:443
  registryUsername: PLACEHOLDER
  registryPassword: PLACEHOLDER
  repositoryPrefix: PLACEHOLDER
  logLevel: info
  cosignPubKey: PLACEHOLDER

resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 128Mi
