apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-core
spec:
  strategy:
    type: Recreate
  template:
    spec:
      serviceAccountName: influxdb-core
      initContainers:
        - name: fix-perms
          image: busybox
          command: ["sh", "-c", "chown -R 1500:1500 /data"]
          env:
            - name: INFLUXDB_KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - secretRef:
                name: influxdb-admin-token
                optional: true
          volumeMounts:
            - mountPath: /data
              name: data
      containers:
        - name: influxdb-core
          image: influxdb:3.9.1-core
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8181
              name: http
              protocol: TCP
          args:
            - --node-id=node0
            - --object-store=file
            - --data-dir=/data
            - --http-bind=[::]:8181
            - --disable-authz=health
          env:
            - name: INFLUXDB_KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - secretRef:
                name: influxdb-admin-token
                optional: true
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          securityContext:
            runAsNonRoot: true
            runAsUser: 1500
            runAsGroup: 1500
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: influxdb-core-data
