apiVersion: v1
kind: ServiceAccount
metadata:
  name: influxdb-core-init
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: influxdb-core-init
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: influxdb-core-init
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: influxdb-core-init
subjects:
  - kind: ServiceAccount
    name: influxdb-core-init
---
apiVersion: batch/v1
kind: Job
metadata:
  name: influxdb-core-init
spec:
  ttlSecondsAfterFinished: 10
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: influxdb-core-init
      initContainers:
        - name: kubectl
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - cp /opt/bitnami/kubectl/bin/kubectl /shared/kubectl && chmod +x /shared/kubectl
          volumeMounts:
            - name: shared-tmp
              mountPath: /shared
      containers:
        - name: influxdb-core
          image: influxdb:3-core
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8181
              name: http
              protocol: TCP
          command:
            - /scripts/influxdb-core-init.sh
          env:
            - name: INFLUXDB_KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - secretRef:
                name: influxdb-admin-token
                optional: true
          securityContext:
            runAsNonRoot: true
            runAsUser: 1500
            runAsGroup: 1500
          volumeMounts:
            - mountPath: /scripts
              name: scripts
            - name: shared-tmp
              mountPath: /tmp
      volumes:
        - name: scripts
          configMap:
            name: influxdb-core-init
            defaultMode: 0777
        - name: shared-tmp
          emptyDir: {}
