apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - namespace.yaml
  - rbac.yaml

namespace: external-dns

secretGenerator:
  - name: cloudflare-secrets
    envs:
      - ./cloudflare-secrets.env

labels:
  - includeSelectors: true
    pairs:
      app: external-dns
