apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cloudflare-api-token.yaml
  - deployment.yaml
  - namespace.yaml
  - rbac.yaml

namespace: external-dns

labels:
  - includeSelectors: true
    pairs:
      app: external-dns
