apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - core/
  ## Disable explorer for now since really much beta
  ## use Grafana for visualization instead
  # - explorer/
