apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: influxdb

resources:
  - namespace.yaml
  - core/
  - telegraf/
  ## Disable explorer for now since really much beta
  ## and the source code is hosted on a private repo
  ## managed by the InfluxDB maintainers.
  ## Use Grafana for visualization instead
  # - explorer/
