apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - namespace.yaml
  - pvc.yaml
  - service.yaml
  - serviceaccount.yaml

namespace: mosquitto

labels:
  - includeSelectors: true
    pairs:
      app: mosquitto

configMapGenerator:
  - name: mosquitto-config
    files:
      - mosquitto.conf

secretGenerator:
  - name: mosquitto-credentials
    files:
      - ./password_file
