apiVersion: v1
kind: Service
metadata:
  name: mosquitto
spec:
  ports:
    - port: 1883
      protocol: TCP
      targetPort: mqtt
      name: mqtt
    - port: 8883
      protocol: TCP
      targetPort: mqtt-tls
      name: mqtt-tls
    - port: 9001
      protocol: TCP
      targetPort: websocket
      name: websocket
    - port: 9443
      protocol: TCP
      targetPort: websocket-tls
      name: websocket-tls
