apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: eg
spec:
  gatewayClassName: eg
  addresses:
    - type: IPAddress
      value: 192.168.110.254
    - type: IPAddress
      value: 2001:1c08:10f:3c02:4a21:bff:fe60:ee00
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      hostname: '*.homie.e10n.me'
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            group: ""
            name: wildcard-certificate
            namespace: cert-manager
          - kind: Secret
            group: ""
            name: otaflux-certs
            namespace: otaflux
