apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: nanomq
spec:
  gatewayClassName: eg
  addresses:
    - type: IPAddress
      value: 192.168.94.254
  listeners:
    - name: mqtts
      protocol: TCP
      port: 8883
      allowedRoutes:
        namespaces:
          from: Same
