apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - pvc.yaml
  - service.yaml
  - serviceaccount.yaml

labels:
  - includeSelectors: true
    pairs:
      app: qbittorrent

secretGenerator:
  - name: gluetun-secrets
    envs:
      - gluetun.env

configMapGenerator:
  - name: qbittorrent-default-config
    files:
      - qBittorrent.conf=qbittorrent-config.yaml
