# Loads default set of integrations. Do not remove.
default_config:

http:
  use_x_forwarded_for: true
  # trust nginx
  trusted_proxies:
    - 10.244.0.0/24

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
