apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - namespace.yaml
  - pvc.yaml
  - service.yaml
  - serviceaccount.yaml

namespace: homeassistant

labels:
  - includeSelectors: true
    pairs:
      app: homeassistant

configMapGenerator:
  - name: configuration
    files:
      - configuration.yaml=homeassistant-configuration.yaml
