kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: homeassistant-config
spec:
  storageClassName: syno-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2G
