apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      grafana_alert: "1"

configMapGenerator:
  - name: alerts
    files:
      - ./no-data-alert.yaml
    options:
      disableNameSuffixHash: true
