grafana.ini:
  users:
    allow_sign_up: false
  auth:
    disable_login_form: false
  auth.basic:
    enabled: true
  auth.anonymous:
    enabled: true

envFromSecrets:
  - name: grafana-secrets

alerting:
  policies.yaml:
    apiVersion: 1
    policies:
      - orgId: 1
        receiver: telegram
        group_by:
          - grafana_folder
          - alertname
  contactpoints.yaml:
    secret:
      apiVersion: 1
      contactPoints:
        - orgId: 1
          name: telegram
          receivers:
            - uid: telegram
              type: telegram
              settings:
                bottoken: ${TELEGRAM_TOKEN}
                chatid: '-4854616166'
                disable_notification: false
                disable_web_page_preview: false
                protect_content: false
                parse_mode: HTML
              disableResolveMessage: false

datasources:
  datasources.yaml:
    apiVersion: 1
    prune: true
    datasources:
      - name: InfluxDB
        uid: influxdb
        type: influxdb
        access: proxy
        url: http://influxdb-core.influxdb.svc.cluster.local:80
        isDefault: true
        user: grafana
        jsonData:
          version: SQL
          dbName: sensors
          httpMode: POST
          insecureGrpc: true
        secureJsonData:
          token: $INFLUXDB_TOKEN

sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    labelValue: "1"
    searchNamespace: grafana
    provider:
      allowUiUpdates: false
  alerts:
    enabled: true
    label: grafana_alert
    labelValue: "1"
    searchNamespace: grafana

testFramework:
  enabled: false
