grafana.ini:
  users:
    allow_sign_up: false

envFromSecrets:
  - name: grafana-datasource-secrets

datasources:
  datasources.yaml:
    apiVersion: 1
    prune: true
    datasources:
      - name: InfluxDB
        uid: influxdb
        type: influxdb
        access: proxy
        url: http://influxdb-core.influxdb.svc.cluster.local:80
        isDefault: true
        user: grafana
        jsonData:
          version: SQL
          dbName: sensors
          httpMode: POST
          insecureGrpc: true
        secureJsonData:
          token: $INFLUXDB_TOKEN

sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    labelValue: "1"
    searchNamespace: grafana
    provider:
      allowUiUpdates: false
    resources:
      limits:
        memory: 64Mi
      requests:
        cpu: 10m
        memory: 64Mi

testFramework:
  enabled: false
